name: Publish UPM Package

on:
  release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: monry/actions-upm-publish@v1
      with:
        npm_auth_token: ${{ secrets.NPM_AUTH_TOKEN }}
